version: "3.8"

services:
  orthanc:
    image: orthancteam/orthanc
    # image: jodogne/orthanc-plugins:1.12.11
    container_name: orthanc
    restart: unless-stopped

    ports:
      - "8042:8042"   # Web UI / REST API
      - "4242:4242"   # DICOM

    volumes:
      - ./orthanc-db:/var/lib/orthanc/db
      - ./orthanc.json:/etc/orthanc/orthanc.json:ro

    environment:
      VERBOSE_ENABLED: "true"
      # you must enable the StoneViewer and the DicomWeb plugins
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      VOLVIEW_PLUGIN_ENABLED: "true"
      OHIF_PLUGIN_ENABLED: "true"

      ORTHANC__DICOM_WEB__SERIES_METADATA: "Full"
      ORTHANC__DICOM_WEB__STUDIES_METADATA: "Full"
      ORTHANC__DICOM_WEB__METADATA_WORKER_THREADS_COUNT : "4"